project_id = "axdwgxtukqqzupboojmx"

[functions.analyze-code]
verify_jwt = false

[functions.simulate-execution]
verify_jwt = false

[functions.generate-ui-preview]
verify_jwt = false

[functions.generate-test-cases]
verify_jwt = false

[functions.generate-rubric]
verify_jwt = false