project_id = "axdwgxtukqqzupboojmx"

[functions.analyze-code]
verify_jwt = false

[functions.simulate-execution]
verify_jwt = false

[functions.generate-ui-preview]
verify_jwt = false

[functions.generate-test-cases]
verify_jwt = false

[functions.generate-rubric]
verify_jwt = false

[functions.realtime-proctoring]
verify_jwt = false

[functions.ai-content-generator]
verify_jwt = false

[functions.enhanced-ai-generator]
verify_jwt = false

[functions.smart-assembly]
verify_jwt = false

[functions.ai-assessment-insights]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = false

[functions.share-assessment]
verify_jwt = false

[functions.enhanced-monitoring-system]
verify_jwt = false

[functions.enhanced-performance-analytics]
verify_jwt = false

[functions.enhanced-report-generator]
verify_jwt = false

[functions.advanced-queue-manager]
verify_jwt = false

[functions.automated-report-scheduler]
verify_jwt = false

[functions.predictive-analytics]
verify_jwt = false

[functions.learning-path-generator]
verify_jwt = false

[functions.fraud-detection-enhanced]
verify_jwt = false

[functions.cohort-analysis]
verify_jwt = false