project_id = "axdwgxtukqqzupboojmx"

[functions.analyze-code]
verify_jwt = false

[functions.simulate-execution]
verify_jwt = false

[functions.generate-ui-preview]
verify_jwt = false

[functions.generate-test-cases]
verify_jwt = false

[functions.generate-rubric]
verify_jwt = false

[functions.realtime-proctoring]
verify_jwt = false

[functions.ai-content-generator]
verify_jwt = false

[functions.ai-assessment-insights]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = false

[functions.share-assessment]
verify_jwt = false